"""empty message

Revision ID: 096a4c4946f5
Revises: 4a5109316351
Create Date: 2025-11-03 02:16:15.764757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096a4c4946f5'
down_revision = '4a5109316351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('ability', sa.String(length=15), nullable=False),
    sa.Column('proficient', sa.Boolean(), nullable=False),
    sa.Column('expert', sa.Boolean(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('character_skills')
    op.drop_table('skills')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ac',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hitDice',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('speed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('initiative',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('proficiency',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('proficiency',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('initiative',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('speed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hitDice',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('ac',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('skills_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=75), autoincrement=False, nullable=False),
    sa.Column('ability', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('proficient', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expert', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='skills_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('character_skills',
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='character_skills_character_id_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='character_skills_skill_id_fkey'),
    sa.PrimaryKeyConstraint('character_id', 'skill_id', name='character_skills_pkey')
    )
    op.drop_table('skill')
    # ### end Alembic commands ###
