"""empty message

Revision ID: 1d06ab73b1ba
Revises: 096a4c4946f5
Create Date: 2025-11-04 00:46:46.111217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d06ab73b1ba'
down_revision = '096a4c4946f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_consumables')
    with op.batch_alter_table('consumable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumable', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('character_id')

    op.create_table('character_consumables',
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consumable_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='character_consumables_character_id_fkey'),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumable.id'], name='character_consumables_consumable_id_fkey'),
    sa.PrimaryKeyConstraint('character_id', 'consumable_id', name='character_consumables_pkey')
    )
    # ### end Alembic commands ###
