"""empty message

Revision ID: 26f07bfa9bc8
Revises: b1d5feaeaee5
Create Date: 2025-10-30 00:15:13.571384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f07bfa9bc8'
down_revision = 'b1d5feaeaee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characterClass', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('subClass', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('ac', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hitDice', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('proficiency', sa.Integer(), nullable=False))
        batch_op.drop_column('hit_dice')
        batch_op.drop_column('char_class')
        batch_op.drop_column('proficiency_bonus')
        batch_op.drop_column('sub_class')
        batch_op.drop_column('armor_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('armor_class', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sub_class', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('proficiency_bonus', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('char_class', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hit_dice', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
        batch_op.drop_column('proficiency')
        batch_op.drop_column('hitDice')
        batch_op.drop_column('ac')
        batch_op.drop_column('subClass')
        batch_op.drop_column('characterClass')

    # ### end Alembic commands ###
