"""empty message

Revision ID: 4a5109316351
Revises: 26f07bfa9bc8
Create Date: 2025-10-31 23:02:39.464862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5109316351'
down_revision = '26f07bfa9bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ac',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hitDice',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('speed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('initiative',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('proficiency',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('proficiency',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('initiative',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('speed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hitDice',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('ac',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
