"""empty message

Revision ID: c1dce388c83b
Revises: 8175ed8f92a0
Create Date: 2025-10-20 23:59:10.690058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1dce388c83b'
down_revision = '8175ed8f92a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_skills',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'skill_id')
    )
   
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('char_class', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('sub_class', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('armor_class', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hit_dice', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('speed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('initiative', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('proficiency_bonus', sa.Integer(), nullable=False))
        batch_op.drop_constraint('character_sub_class_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('character_char_class_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('character_race_id_fkey', type_='foreignkey')
        batch_op.drop_column('race_id')
        batch_op.drop_column('char_class_id')
        batch_op.drop_column('sub_class_id')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ability', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('proficient', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('expert', sa.Boolean(), nullable=False))
        batch_op.drop_column('modifier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modifier', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
        batch_op.drop_column('expert')
        batch_op.drop_column('proficient')
        batch_op.drop_column('ability')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_class_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('char_class_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('race_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('character_race_id_fkey', 'race', ['race_id'], ['id'])
        batch_op.create_foreign_key('character_char_class_id_fkey', 'char_class', ['char_class_id'], ['id'])
        batch_op.create_foreign_key('character_sub_class_id_fkey', 'sub_class', ['sub_class_id'], ['id'])
        batch_op.drop_column('proficiency_bonus')
        batch_op.drop_column('initiative')
        batch_op.drop_column('speed')
        batch_op.drop_column('hit_dice')
        batch_op.drop_column('armor_class')
        batch_op.drop_column('hp')
        batch_op.drop_column('level')
        batch_op.drop_column('sub_class')
        batch_op.drop_column('char_class')
        batch_op.drop_column('race')

    op.create_table('sub_class',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sub_class_pkey')
    )
    op.create_table('race',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='race_pkey')
    )
    op.create_table('char_class',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='char_class_pkey')
    )
    op.drop_table('character_skills')
    # ### end Alembic commands ###
