// src/data/items.js

export const inventory = [
  {
    id: 1,
    name: "Longsword",
    type: "weapon",
    rarity: "common",
    description: "A standard steel longsword. Reliable and sharp.",
    weight: 3,
    value: 15,
    quantity: 1,
    equipped: true,
    icon: "/icons/longsword.png",
    stats: {
      damage: "1d8 slashing",
      properties: ["Versatile (1d10)"],
    },
  },
  {
    id: 2,
    name: "Shortbow",
    type: "weapon",
    rarity: "uncommon",
    description: "A light, flexible bow with a leather grip.",
    weight: 2,
    value: 25,
    quantity: 1,
    equipped: false,
    icon: "/icons/shortbow.png",
    stats: {
      damage: "1d6 piercing",
      properties: ["Ammunition (range 80/320)", "Two-Handed"],
    },
  },
  {
    id: 3,
    name: "Leather Armor",
    type: "armor",
    rarity: "common",
    description: "Supple leather armor offering basic protection.",
    weight: 10,
    value: 10,
    quantity: 1,
    equipped: true,
    icon: "/icons/leather-armor.png",
    stats: {
      armorClass: 11,
      stealthDisadvantage: false,
    },
  },
  {
    id: 4,
    name: "Potion of Healing",
    type: "consumable",
    rarity: "common",
    description: "Restores 2d4 + 2 hit points when consumed.",
    weight: 0.5,
    value: 50,
    quantity: 3,
    equipped: false,
    icon: "/icons/healing-potion.png",
    stats: {
      healAmount: "2d4 + 2",
    },
  },
  {
    id: 5,
    name: "Ring of Protection",
    type: "accessory",
    rarity: "rare",
    description: "Grants a +1 bonus to AC and saving throws.",
    weight: 0.1,
    value: 200,
    quantity: 1,
    equipped: true,
    icon: "/icons/ring-of-protection.png",
    stats: {
      bonusAC: "+1",
      bonusSave: "+1",
    },
  },
  {
    id: 6,
    name: "Rope (50 feet)",
    type: "gear",
    rarity: "common",
    description: "A sturdy hemp rope. Useful for climbing or tying things.",
    weight: 10,
    value: 1,
    quantity: 1,
    equipped: false,
    icon: "/icons/rope.png",
  },
  {
    id: 7,
    name: "Bag of Holding",
    type: "gear",
    rarity: "rare",
    description:
      "A magical bag that can hold up to 500 pounds, not exceeding 64 cubic feet.",
    weight: 15,
    value: 4000,
    quantity: 1,
    equipped: false,
    icon: "/icons/bag-of-holding.png",
  },
  {
    id: 8,
    name: "Torch",
    type: "gear",
    rarity: "common",
    description: "Provides light in a 20-foot radius when lit.",
    weight: 1,
    value: 0.1,
    quantity: 5,
    equipped: false,
    icon: "/icons/torch.png",
  },
  {
    id: 9,
    name: "Spellbook",
    type: "magic",
    rarity: "uncommon",
    description: "Contains a wizard's collection of prepared spells.",
    weight: 3,
    value: 75,
    quantity: 1,
    equipped: false,
    icon: "/icons/spellbook.png",
  },
  {
    id: 10,
    name: "Amulet of the Nightwatcher",
    type: "accessory",
    rarity: "legendary",
    description:
      "Ancient relic granting darkvision and protection from charm effects.",
    weight: 0.2,
    value: 5000,
    quantity: 1,
    equipped: false,
    icon: "/icons/amulet.png",
    stats: {
      effect: ["Darkvision 60ft", "Advantage on charm saves"],
    },
  },
];
